from .LinearRegression import LinearRegression
from .LogisticRegression import LogisticRegression
from .DecisionTreeClassifier import DecisionTreeClassifier
from .KNNClassifier import KNNClassifier
from .KNNRegressor import KNNRegressor
from .ShallowNeuralNetwork import ShallowNeuralNetwork
from .DeepNeuralNetwork import DeepNeuralNetwork
from .OneVsRestClassifier import OneVsRestClassifier